// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260905155244_Walks_Data_Seed")]
    partial class Walks_Data_Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("9c858901-8a57-4791-81fe-4c455b099bc9"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("6ba7b810-9dad-41d1-80b4-00c04fd430c8"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f7c2d1a-5b34-4e91-a7c2-1d6f9b8e3a45"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://dummyjson.com/image/800x600/0088cc/ffffff?text=Auckland"
                        },
                        new
                        {
                            Id = new Guid("3a9e6c72-1f45-4b8d-b2c7-6e5a1d9f3048"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://dummyjson.com/image/800x600/44aa88/ffffff?text=Wellington"
                        },
                        new
                        {
                            Id = new Guid("c4b82e17-6d39-4f25-9a71-3e8c5b2d604f"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageUrl = "https://dummyjson.com/image/800x600/aa8844/ffffff?text=Canterbury"
                        },
                        new
                        {
                            Id = new Guid("7d1f93a6-2c58-4e74-b9a3-5f6d8c1b2047"),
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageUrl = "https://dummyjson.com/image/800x600/6644aa/ffffff?text=Otago"
                        },
                        new
                        {
                            Id = new Guid("e5a27c91-4b63-48d0-8f35-1c7e9a2b6054"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://dummyjson.com/image/800x600/aa4466/ffffff?text=Waikato"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f16afa0-e33f-4bef-1a9d-08df0b2dbd77"),
                            Description = "A challenging hike near Wanaka with spectacular panoramic views of Lake Wanaka and the surrounding Southern Alps.",
                            DifficultyId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            LengthInKm = 16.0,
                            Name = "Roy's Peak Track",
                            RegionId = new Guid("c4b82e17-6d39-4f25-9a71-3e8c5b2d604f"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/228833/ffffff?text=Roy's+Peak+Track"
                        },
                        new
                        {
                            Id = new Guid("c084fa5b-8caa-48d2-d26e-08df0b2e21f8"),
                            Description = "A scenic multi-day hike through native forests with beautiful views of Lake Waikaremoana and the surrounding wilderness.",
                            DifficultyId = new Guid("6ba7b810-9dad-41d1-80b4-00c04fd430c8"),
                            LengthInKm = 46.0,
                            Name = "Lake Waikaremoana Track",
                            RegionId = new Guid("7d1f93a6-2c58-4e74-b9a3-5f6d8c1b2047"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/336699/ffffff?text=Lake+Waikaremoana+Track"
                        },
                        new
                        {
                            Id = new Guid("c720780a-1830-4b70-52ae-08df0b52e142"),
                            Description = "An easy and scenic walk through the Southern Alps with spectacular views of Aoraki Mount Cook, glaciers, rivers, and mountain landscapes.",
                            DifficultyId = new Guid("9c858901-8a57-4791-81fe-4c455b099bc9"),
                            LengthInKm = 10.0,
                            Name = "Hooker Valley Track",
                            RegionId = new Guid("8f7c2d1a-5b34-4e91-a7c2-1d6f9b8e3a45"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/884422/ffffff?text=Hooker+Valley+Track"
                        },
                        new
                        {
                            Id = new Guid("215fc389-fa83-43b9-bb5e-08df0b5447cd"),
                            Description = "One of New Zealand's most famous multi-day hiking tracks through spectacular mountains, forests, and valleys.",
                            DifficultyId = new Guid("9c858901-8a57-4791-81fe-4c455b099bc9"),
                            LengthInKm = 53.5,
                            Name = "Milford Track",
                            RegionId = new Guid("8f7c2d1a-5b34-4e91-a7c2-1d6f9b8e3a45"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/225588/ffffff?text=Milford+Track"
                        },
                        new
                        {
                            Id = new Guid("a13f6c92-7e41-4b85-9d26-5c8a17f304be"),
                            Description = "A challenging alpine hike offering spectacular views across Taranaki and the surrounding landscapes.",
                            DifficultyId = new Guid("6ba7b810-9dad-41d1-80b4-00c04fd430c8"),
                            LengthInKm = 18.5,
                            Name = "Mount Taranaki Summit Track",
                            RegionId = new Guid("e5a27c91-4b63-48d0-8f35-1c7e9a2b6054"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/446688/ffffff?text=Mount+Taranaki+Summit+Track"
                        },
                        new
                        {
                            Id = new Guid("b72e491c-35a8-4f67-a129-8d6c20e5b743"),
                            Description = "A scenic and accessible walk through native bush leading to panoramic views over Wellington city and harbour.",
                            DifficultyId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            LengthInKm = 5.2000000000000002,
                            Name = "Mount Victoria Lookout",
                            RegionId = new Guid("3a9e6c72-1f45-4b8d-b2c7-6e5a1d9f3048"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/228855/ffffff?text=Mount+Victoria+Lookout"
                        },
                        new
                        {
                            Id = new Guid("c46d8a21-9f53-47be-b630-1e7c95a2d804"),
                            Description = "A relaxing riverside walk through parks and native vegetation with beautiful views along the Waikato River.",
                            DifficultyId = new Guid("9c858901-8a57-4791-81fe-4c455b099bc9"),
                            LengthInKm = 8.4000000000000004,
                            Name = "Hamilton River Walk",
                            RegionId = new Guid("e5a27c91-4b63-48d0-8f35-1c7e9a2b6054"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/338866/ffffff?text=Hamilton+River+Walk"
                        },
                        new
                        {
                            Id = new Guid("d85b237a-61c4-49e8-a572-3f9b16c74028"),
                            Description = "A beautiful forest trail through lush native bush with waterfalls, streams, and impressive coastal views.",
                            DifficultyId = new Guid("9c858901-8a57-4791-81fe-4c455b099bc9"),
                            LengthInKm = 12.699999999999999,
                            Name = "Waitakere Ranges Trail",
                            RegionId = new Guid("8f7c2d1a-5b34-4e91-a7c2-1d6f9b8e3a45"),
                            WalkImageUrl = "https://dummyjson.com/image/800x600/557744/ffffff?text=Waitakere+Ranges+Trail"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
